<?php
declare(strict_types=1);
namespace Archium\Controllers;
use Archium\Repositories\AclRepository;
use Archium\Repositories\CollectionRepository;
use Archium\Repositories\DocumentRepository;
use Archium\Repositories\GroupRepository;
use Archium\Repositories\WorkspaceMemberRepository;
use Archium\Services\PermissionResolver;
use Archium\Support\Auth;
use Archium\Support\Csrf;
use Archium\Support\Database;
use Archium\Repositories\WorkspaceRepository;

final class AclController extends BaseController
{
    private function pdo():\PDO{return Database::connection($this->config);}
    private function resolver():PermissionResolver{$p=$this->pdo();return new PermissionResolver(new WorkspaceRepository($p),new AclRepository($p),new GroupRepository($p));}
    private function subjects(array $ws):array{$p=$this->pdo();return ['users'=>(new WorkspaceMemberRepository($p))->forWorkspace((int)$ws['id']),'groups'=>(new GroupRepository($p))->forWorkspace((int)$ws['id'])];}
    public function collection(string $id):string{$ws=$this->currentWorkspace();$u=Auth::user($this->config);$p=$this->pdo();$col=(new CollectionRepository($p))->findInWorkspace((int)$id,(int)$ws['id']);if(!$col){http_response_code(404);return 'Raccolta non trovata.';}if(!$this->resolver()->canCollection((int)$ws['id'],(int)$id,(int)$u['id'],'admin')){http_response_code(403);return 'Accesso negato.';}$s=$this->subjects($ws);return $this->view('acl/collection',['pageTitle'=>'Permessi raccolta','ws'=>$ws,'collection'=>$col,'entries'=>(new AclRepository($p))->collectionEntries((int)$id),'users'=>$s['users'],'groups'=>$s['groups']]);}
    public function document(string $id):string{$ws=$this->currentWorkspace();$u=Auth::user($this->config);$p=$this->pdo();$doc=(new DocumentRepository($p))->findInWorkspace((int)$id,(int)$ws['id']);if(!$doc){http_response_code(404);return 'Documento non trovato.';}if(!$this->resolver()->canDocument((int)$ws['id'],(int)$id,$doc['collection_id']!==null?(int)$doc['collection_id']:null,(int)$u['id'],'admin')){http_response_code(403);return 'Accesso negato.';}$s=$this->subjects($ws);$inherited=$doc['collection_id']!==null?(new AclRepository($p))->collectionEntries((int)$doc['collection_id']):[];return $this->view('acl/document',['pageTitle'=>'Permessi documento','ws'=>$ws,'document'=>$doc,'entries'=>(new AclRepository($p))->documentEntries((int)$id),'inherited'=>$inherited,'users'=>$s['users'],'groups'=>$s['groups']]);}
    public function grantCollection(string $id):string{Csrf::requireValid();$ws=$this->currentWorkspace();$u=Auth::user($this->config);$p=$this->pdo();$col=(new CollectionRepository($p))->findInWorkspace((int)$id,(int)$ws['id']);if(!$col||!$this->resolver()->canCollection((int)$ws['id'],(int)$id,(int)$u['id'],'admin')){http_response_code(403);return 'Accesso negato.';}$this->grant('collection',(int)$id,(int)$ws['id']);redirect('/collections/'.(int)$id.'/acl');}
    public function grantDocument(string $id):string{Csrf::requireValid();$ws=$this->currentWorkspace();$u=Auth::user($this->config);$p=$this->pdo();$doc=(new DocumentRepository($p))->findInWorkspace((int)$id,(int)$ws['id']);if(!$doc||!$this->resolver()->canDocument((int)$ws['id'],(int)$id,$doc['collection_id']!==null?(int)$doc['collection_id']:null,(int)$u['id'],'admin')){http_response_code(403);return 'Accesso negato.';}$this->grant('document',(int)$id,(int)$ws['id']);redirect('/documents/'.(int)$id.'/acl');}
    public function revokeCollection(string $id,string $type,string $subject):string{Csrf::requireValid();$ws=$this->currentWorkspace();$u=Auth::user($this->config);$p=$this->pdo();if(!in_array($type,['user','group'],true)||!$this->resolver()->canCollection((int)$ws['id'],(int)$id,(int)$u['id'],'admin')){http_response_code(403);return 'Accesso negato.';}(new AclRepository($p))->revokeCollection($type,(int)$id,(int)$subject);flash('success','Assegnazione rimossa.');redirect('/collections/'.(int)$id.'/acl');}
    public function revokeDocument(string $id,string $type,string $subject):string{Csrf::requireValid();$ws=$this->currentWorkspace();$u=Auth::user($this->config);$p=$this->pdo();$doc=(new DocumentRepository($p))->findInWorkspace((int)$id,(int)$ws['id']);if(!$doc||!in_array($type,['user','group'],true)||!$this->resolver()->canDocument((int)$ws['id'],(int)$id,$doc['collection_id']!==null?(int)$doc['collection_id']:null,(int)$u['id'],'admin')){http_response_code(403);return 'Accesso negato.';}(new AclRepository($p))->revokeDocument($type,(int)$id,(int)$subject);flash('success','Override rimosso.');redirect('/documents/'.(int)$id.'/acl');}
    private function grant(string $scope,int $resourceId,int $workspaceId):void{$type=(string)($_POST['subject_type']??'user');$role=(string)($_POST['role']??'viewer');$ids=array_values(array_unique(array_map('intval',(array)($_POST['subject_ids']??[]))));if(!in_array($type,['user','group'],true)||!in_array($role,['viewer','editor','admin'],true)||$ids===[]){flash('error','Seleziona almeno un soggetto e un ruolo valido.');return;}$p=$this->pdo();if($type==='user'){$valid=array_map(fn($m)=>(int)$m['user_id'],(new WorkspaceMemberRepository($p))->forWorkspace($workspaceId));$ids=array_values(array_intersect($ids,$valid));}else{$valid=array_map(fn($g)=>(int)$g['id'],(new GroupRepository($p))->forWorkspace($workspaceId));$ids=array_values(array_intersect($ids,$valid));}$acl=new AclRepository($p);if($ids===[]){flash('error','Nessun soggetto valido selezionato.');return;}if($scope==='collection'){if($type==='user')$acl->grantCollectionUsers($resourceId,$ids,$role);else $acl->grantCollectionGroups($resourceId,$ids,$role);}else{if($type==='user')$acl->grantDocumentUsers($resourceId,$ids,$role);else $acl->grantDocumentGroups($resourceId,$ids,$role);}flash('success','Permessi applicati a '.count($ids).' soggetti.');}
}